import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

import {
  MatButtonModule,
  MatCheckboxModule,
  MatMenuModule,
  MatIconModule,
  MatListModule,
  MatTableModule,
  MatFormFieldModule,
  MatTooltipModule,
  MatInputModule,
  MatExpansionModule,
  MatPaginatorModule,
  MatDialogModule,
  MatTabsModule,
  MatAutocompleteModule,
  MatSelectModule,
  MatGridListModule,
  MatCardModule,
  MatToolbarModule,
  MatDividerModule,
  MatSortModule,
  MatProgressSpinnerModule,
  MatDatepickerModule,
  MatProgressBarModule,
  MatSlideToggleModule,
  MatRadioModule,
  MatSnackBarModule
} from '@angular/material';

@NgModule({
  imports: [
    CommonModule,
    BrowserAnimationsModule,

    MatButtonModule,
    MatCheckboxModule,
    MatMenuModule,
    MatIconModule,
    MatListModule,
    MatTableModule,
    MatFormFieldModule,
    MatTooltipModule,
    MatInputModule,
    MatExpansionModule,
    MatPaginatorModule,
    MatDialogModule,
    MatTabsModule,
    MatAutocompleteModule,
    MatSelectModule,
    MatCardModule,
    MatGridListModule,
    MatToolbarModule,
    MatDividerModule,
    MatSortModule,
    MatProgressSpinnerModule,
    MatDatepickerModule,
    MatProgressBarModule,
    MatRadioModule,
    MatSlideToggleModule,
    MatSnackBarModule
  ],
  exports: [
    BrowserAnimationsModule,

    MatButtonModule,
    MatCheckboxModule,
    MatMenuModule,
    MatIconModule,
    MatListModule,
    MatTableModule,
    MatFormFieldModule,
    MatTooltipModule,
    MatInputModule,
    MatExpansionModule,
    MatPaginatorModule,
    MatDialogModule,
    MatTabsModule,
    MatAutocompleteModule,
    MatSelectModule,
    MatCardModule,
    MatGridListModule,
    MatToolbarModule,
    MatToolbarModule,
    MatDividerModule,
    MatSortModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatDatepickerModule,
    MatRadioModule,
    MatSlideToggleModule,
    MatSnackBarModule
  ],
  declarations: []
})
export class CoreModule { }
